import { Router } from "express";
import {
  agregarAnimalController,
  agregarBoletaController,
  agregarCapacitacionController,
  agregarCitaMedicaController,
  agregarEmpleadoController,
  agregarEstadoHabitatController,
  agregarEstadoSaludController,
  agregarEventoController,
  agregarFacturaEntradaController,
  agregarHabitatController,
  agregarHistorialSaludController,
  agregarHorarioAlimentacionController,
  agregarHorarioTrabajoController,
  agregarListaBoletasController,
  agregarPlanificacionEventosController,
  agregarPromocionesController,
  agregarPuestoController,
  agregarSeguimientoEmpleadoController,
  agregarTipoAlimentacionController,
  agregarTipoBoletaController,
  agregarZonaController,
} from "../controllers/postControllers.js";
import {
  postAnimalDTOMiddleware,
  postBoletasDTOMiddleware,
  postCapacitacionDTOMiddleware,
  postCitasMedicasDTOMiddleware,
  postEmpleadoDTOMiddleware,
  postEstadoHabitatDTOMiddleware,
  postEvaluacionDesempenoDTOMiddleware,
  postEventoDTOMiddleware,
  postFacturaEntradaDTOMiddleware,
  postHabitatDTOMiddleware,
  postHistorialEventosDTOMiddleware,
  postHistorialSaludDTOMiddleware,
  postHorarioAlimentacionDTOMiddleware,
  postHorarioTrabajoDTOMiddleware,
  postListaBoletasDTOMiddleware,
  postPlanificacionEventosDTOMiddleware,
  postPromocionesDTOMiddleware,
  postPuestosDTOMiddleware,
  postSeguimientoEmpleadoDTOMiddleware,
  postTipoAlimentacionDTOMiddleware,
  postTiposBoletasDTOMiddleware,
  postZonasDTOMiddleware,
  postestadoSaludDTOMiddleware,
} from "../middlewares/middlewaresDTO.js";
import {
  authorizationMiddleware,
  contentMiddlewareAlimentacion,
  contentMiddlewareAnimales,
  contentMiddlewareBoletas,
  contentMiddlewareCapacitaciones,
  contentMiddlewareCitasMedicas,
  contentMiddlewareEmpleados,
  contentMiddlewareEstadoHabitat,
  contentMiddlewareEstadoSalud,
  contentMiddlewareEvaluacionDesempeno,
  contentMiddlewareEventos,
  contentMiddlewareFacturaEntrada,
  contentMiddlewareHabitat,
  contentMiddlewareHistorialEventos,
  contentMiddlewareHistorialesSalud,
  contentMiddlewareHorariosAlimentacion,
  contentMiddlewareHorariosTrabajo,
  contentMiddlewareListaBoletas,
  contentMiddlewarePlanificacionEventos,
  contentMiddlewarePromociones,
  contentMiddlewarePuestos,
  contentMiddlewareSeguimientoEmpleados,
  contentMiddlewareTipoBoleta,
  contentMiddlewareZonas,
} from "../middlewares/middlewareContent.js";
import { rolVerificatorMiddlewareAdmin, rolVerificatorMiddlewareJefePersonal, rolVerificatorMiddlewareMedico, rolVerificatorMiddlewareStaff, rolVerificatorMiddlewareTaquillero } from "../middlewares/rolVerificationMiddlewares.js";

const postInitRoute = () => {
  const router = Router();
  router.post(
    "/agregarTipoAlimentacion",
    authorizationMiddleware,
    rolVerificatorMiddlewareMedico,
    contentMiddlewareAlimentacion,
    postTipoAlimentacionDTOMiddleware,
    agregarTipoAlimentacionController
  );
  router.post(
    "/agregarAnimal",
    authorizationMiddleware,
    rolVerificatorMiddlewareAdmin,
    contentMiddlewareAnimales,
    postAnimalDTOMiddleware,
    agregarAnimalController
  );
  router.post(
    "/agregarBoletas",
    authorizationMiddleware,
    rolVerificatorMiddlewareTaquillero,
    contentMiddlewareBoletas,
    postBoletasDTOMiddleware,
    agregarBoletaController
  );
  router.post(
    "/agregarCapitacion",
    authorizationMiddleware,
    rolVerificatorMiddlewareJefePersonal,
    contentMiddlewareCapacitaciones,
    postCapacitacionDTOMiddleware,
    agregarCapacitacionController
  );
  router.post(
    "/agregarCitaMedica",
    authorizationMiddleware,
    rolVerificatorMiddlewareMedico,
    contentMiddlewareCitasMedicas,
    postCitasMedicasDTOMiddleware,
    agregarCitaMedicaController
  );
  router.post(
    "/agregarEmpleado",
    authorizationMiddleware,
    rolVerificatorMiddlewareJefePersonal,
    contentMiddlewareEmpleados,
    postEmpleadoDTOMiddleware,
    agregarEmpleadoController
  );
  router.post(
    "/agregarEstadoHabitat",
    authorizationMiddleware,
    rolVerificatorMiddlewareStaff,
    contentMiddlewareEstadoHabitat,
    postEstadoHabitatDTOMiddleware,
    agregarEstadoHabitatController
  );
  router.post(
    "/agregarEstadoSalud",
    authorizationMiddleware,
    rolVerificatorMiddlewareMedico,
    contentMiddlewareEstadoSalud,
    postestadoSaludDTOMiddleware,
    agregarEstadoSaludController
  );
  router.post(
    "/agregarEvaluacionDesempeno",
    authorizationMiddleware,
    rolVerificatorMiddlewareJefePersonal,
    contentMiddlewareEvaluacionDesempeno,
    postEvaluacionDesempenoDTOMiddleware,
    agregarEmpleadoController
  );
  router.post(
    "/agregarEventos",
    authorizationMiddleware,
    rolVerificatorMiddlewareStaff,
    contentMiddlewareEventos,
    postEventoDTOMiddleware,
    agregarEventoController
  );
  router.post(
    "/agregarFacturaEntrada",
    authorizationMiddleware,
    rolVerificatorMiddlewareTaquillero,
    contentMiddlewareFacturaEntrada,
    postFacturaEntradaDTOMiddleware,
    agregarFacturaEntradaController
  );
  router.post(
    "/agregarHabitat",
    authorizationMiddleware,
    rolVerificatorMiddlewareAdmin,
    contentMiddlewareHabitat,
    postHabitatDTOMiddleware,
    agregarHabitatController
  );
  router.post(
    "/agregarHistorialSalud",
    authorizationMiddleware,
    rolVerificatorMiddlewareMedico,
    contentMiddlewareHistorialesSalud,
    postHistorialSaludDTOMiddleware,
    agregarHistorialSaludController
  );
  router.post(
    "/agregarHistorialEvento",
    authorizationMiddleware,
    rolVerificatorMiddlewareStaff,
    contentMiddlewareHistorialEventos,
    postHistorialEventosDTOMiddleware,
    agregarEmpleadoController
  );
  router.post(
    "/agregarHorariosAlimentacion",
    authorizationMiddleware,
    rolVerificatorMiddlewareStaff,
    contentMiddlewareHorariosAlimentacion,
    postHorarioAlimentacionDTOMiddleware,
    agregarHorarioAlimentacionController
  );
  router.post(
    "/agregarHorarioTrabajo",
    authorizationMiddleware,
    rolVerificatorMiddlewareJefePersonal,
    contentMiddlewareHorariosTrabajo,
    postHorarioTrabajoDTOMiddleware,
    agregarHorarioTrabajoController
  );
  router.post(
    "/agregarListaBoletas",
    authorizationMiddleware,
    rolVerificatorMiddlewareTaquillero,
    contentMiddlewareListaBoletas,
    postListaBoletasDTOMiddleware,
    agregarListaBoletasController
  );
  router.post(
    "/agregarPlanificacionEvento",
    authorizationMiddleware,
    rolVerificatorMiddlewareStaff,
    contentMiddlewarePlanificacionEventos,
    postPlanificacionEventosDTOMiddleware,
    agregarPlanificacionEventosController
  );
  router.post(
    "/agregarPromocion",
    authorizationMiddleware,
    rolVerificatorMiddlewareTaquillero,
    contentMiddlewarePromociones,
    postPromocionesDTOMiddleware,
    agregarPromocionesController
  );
  router.post(
    "/agregarPuesto",
    authorizationMiddleware,
    rolVerificatorMiddlewareJefePersonal,
    contentMiddlewarePuestos,
    postPuestosDTOMiddleware,
    agregarPuestoController
  );
  router.post(
    "/agregarSeguimientoEmpleado",
    authorizationMiddleware,
    rolVerificatorMiddlewareJefePersonal,
    contentMiddlewareSeguimientoEmpleados,
    postSeguimientoEmpleadoDTOMiddleware,
    agregarSeguimientoEmpleadoController
  );
  router.post(
    "/agregarTipoBoleta",
    authorizationMiddleware,
    rolVerificatorMiddlewareTaquillero,
    contentMiddlewareTipoBoleta,
    postTiposBoletasDTOMiddleware,
    agregarTipoBoletaController
  );
  router.post(
    "/agregarZona",
    authorizationMiddleware,
    rolVerificatorMiddlewareAdmin,
    contentMiddlewareZonas,
    postZonasDTOMiddleware,
    agregarZonaController
  );
  return router;
};

export { postInitRoute };
