import { Router } from "express";
import {
  actualizarAnimalController,
  actualizarBoletaController,
  actualizarCapacitacionController,
  actualizarCitaMedicaController,
  actualizarEmpleadoController,
  actualizarEstadoHabitatController,
  actualizarEstadoSaludController,
  actualizarEvaluacionDesempenoController,
  actualizarEventoController,
  actualizarFacturaEntradaController,
  actualizarHabitatController,
  actualizarHistorialEventoController,
  actualizarHistorialSaludController,
  actualizarHorarioAlimentacionController,
  actualizarHorarioTrabajoController,
  actualizarListaBoletasController,
  actualizarPlanificacionEventosController,
  actualizarPromocionesController,
  actualizarPuestoController,
  actualizarSeguimientoEmpleadoController,
  actualizarTipoAlimentacionController,
  actualizarTipoBoletaController,
  actualizarZonaController,
} from "../controllers/putControllers.js";
import {
  postEmpleadoDTOMiddleware,
  putAnimalDTOMiddleware,
  putBoletasDTOMiddleware,
  putCapacitacionDTOMiddleware,
  putCitasMedicasDTOMiddleware,
  putEstadoHabitatDTOMiddleware,
  putEvaluacionDesempenoDTOMiddleware,
  putEventoDTOMiddleware,
  putFacturaEntradaDTOMiddleware,
  putHabitatDTOMiddleware,
  putHistorialEventosDTOMiddleware,
  putHistorialSaludDTOMiddleware,
  putHorarioAlimentacionDTOMiddleware,
  putHorarioTrabajoDTOMiddleware,
  putListaBoletasDTOMiddleware,
  putPlanificacionEventosDTOMiddleware,
  putPromocionesDTOMiddleware,
  putPuestosDTOMiddleware,
  putSeguimientoEmpleadoDTOMiddleware,
  putTipoAlimentacionDTOMiddleware,
  putTiposBoletasDTOMiddleware,
  putZonasDTOMiddleware,
  putestadoSaludDTOMiddleware,
} from "../middlewares/middlewaresDTO.js";
import {
  authorizationMiddleware,
  contentMiddlewareAlimentacion,
  contentMiddlewareAnimales,
  contentMiddlewareBoletas,
  contentMiddlewareCapacitaciones,
  contentMiddlewareCitasMedicas,
  contentMiddlewareEmpleados,
  contentMiddlewareEstadoHabitat,
  contentMiddlewareEstadoSalud,
  contentMiddlewareEvaluacionDesempeno,
  contentMiddlewareEventos,
  contentMiddlewareFacturaEntrada,
  contentMiddlewareHabitat,
  contentMiddlewareHistorialEventos,
  contentMiddlewareHistorialesSalud,
  contentMiddlewareHorariosAlimentacion,
  contentMiddlewareHorariosTrabajo,
  contentMiddlewareListaBoletas,
  contentMiddlewarePlanificacionEventos,
  contentMiddlewarePromociones,
  contentMiddlewarePuestos,
  contentMiddlewareSeguimientoEmpleados,
  contentMiddlewareTipoBoleta,
  contentMiddlewareZonas,
} from "../middlewares/middlewareContent.js";
import { rolVerificatorMiddlewareAdmin, rolVerificatorMiddlewareJefePersonal, rolVerificatorMiddlewareMedico, rolVerificatorMiddlewareStaff, rolVerificatorMiddlewareTaquillero } from "../middlewares/rolVerificationMiddlewares.js";

const putInitRoute = () => {
  const router = Router();
  router.put(
    "/actualizarTipoAlimentacion",
    authorizationMiddleware,
    rolVerificatorMiddlewareMedico,
    contentMiddlewareAlimentacion,
    putTipoAlimentacionDTOMiddleware,
    actualizarTipoAlimentacionController
  );
  router.put(
    "/actualizarAnimal",
    authorizationMiddleware,
    rolVerificatorMiddlewareMedico,
    contentMiddlewareAnimales,
    putAnimalDTOMiddleware,
    actualizarAnimalController
  );
  router.put(
    "/actualizarBoleta",
    authorizationMiddleware,
    rolVerificatorMiddlewareTaquillero,
    contentMiddlewareBoletas,
    putBoletasDTOMiddleware,
    actualizarBoletaController
  );
  router.put(
    "/actualizarCapacitacion",
    authorizationMiddleware,
    rolVerificatorMiddlewareJefePersonal,
    contentMiddlewareCapacitaciones,
    putCapacitacionDTOMiddleware,
    actualizarCapacitacionController
  );
  router.put(
    "/actualizarCitaMedica",
    authorizationMiddleware,
    rolVerificatorMiddlewareMedico,
    contentMiddlewareCitasMedicas,
    putCitasMedicasDTOMiddleware,
    actualizarCitaMedicaController
  );
  router.put(
    "/actualizarEmpleado",
    authorizationMiddleware,
    rolVerificatorMiddlewareJefePersonal,
    contentMiddlewareEmpleados,
    postEmpleadoDTOMiddleware,
    actualizarEmpleadoController
  );
  router.put(
    "/actualizarEstadoHabitat",
    authorizationMiddleware,
    rolVerificatorMiddlewareStaff,
    contentMiddlewareEstadoHabitat,
    putEstadoHabitatDTOMiddleware,
    actualizarEstadoHabitatController
  );
  router.put(
    "/actualizarEstadoSalud",
    authorizationMiddleware,
    rolVerificatorMiddlewareMedico,
    contentMiddlewareEstadoSalud,
    putestadoSaludDTOMiddleware,
    actualizarEstadoSaludController
  );
  router.put(
    "/actualizarEvaluacion",
    authorizationMiddleware,
    rolVerificatorMiddlewareJefePersonal,
    contentMiddlewareEvaluacionDesempeno,
    putEvaluacionDesempenoDTOMiddleware,
    actualizarEvaluacionDesempenoController
  );
  router.put(
    "/actualizarEvento",
    authorizationMiddleware,
    rolVerificatorMiddlewareAdmin,
    contentMiddlewareEventos,
    putEventoDTOMiddleware,
    actualizarEventoController
  );
  router.put(
    "/actualizarFactura",
    authorizationMiddleware,
    rolVerificatorMiddlewareTaquillero,
    contentMiddlewareFacturaEntrada,
    putFacturaEntradaDTOMiddleware,
    actualizarFacturaEntradaController
  );
  router.put(
    "/actualizarHabitat",
    authorizationMiddleware,
    rolVerificatorMiddlewareStaff,
    contentMiddlewareHabitat,
    putHabitatDTOMiddleware,
    actualizarHabitatController
  );
  router.put(
    "/actualizarHistorialSalud",
    authorizationMiddleware,
    rolVerificatorMiddlewareMedico,
    contentMiddlewareHistorialesSalud,
    putHistorialSaludDTOMiddleware,
    actualizarHistorialSaludController
  );
  router.put(
    "/actualizarHistorialEvento",
    authorizationMiddleware,
    rolVerificatorMiddlewareStaff,
    contentMiddlewareHistorialEventos,
    putHistorialEventosDTOMiddleware,
    actualizarHistorialEventoController
  );
  router.put(
    "/actualizarHorarioAlimentacion",
    authorizationMiddleware,
    rolVerificatorMiddlewareMedico,
    contentMiddlewareHorariosAlimentacion,
    putHorarioAlimentacionDTOMiddleware,
    actualizarHorarioAlimentacionController
  );
  router.put(
    "/actualizarHorarioTrabajo",
    authorizationMiddleware,
    rolVerificatorMiddlewareJefePersonal,
    contentMiddlewareHorariosTrabajo,
    putHorarioTrabajoDTOMiddleware,
    actualizarHorarioTrabajoController
  );
  router.put(
    "/actualizarListaBoletas",
    authorizationMiddleware,
    rolVerificatorMiddlewareTaquillero,
    contentMiddlewareListaBoletas,
    putListaBoletasDTOMiddleware,
    actualizarListaBoletasController
  );
  router.put(
    "/actualizarPlanificacionEventos",
    authorizationMiddleware,
    rolVerificatorMiddlewareAdmin,
    contentMiddlewarePlanificacionEventos,
    putPlanificacionEventosDTOMiddleware,
    actualizarPlanificacionEventosController
  );
  router.put(
    "/actualizarPromociones",
    authorizationMiddleware,
    rolVerificatorMiddlewareTaquillero,
    contentMiddlewarePromociones,
    putPromocionesDTOMiddleware,
    actualizarPromocionesController
  );
  router.put(
    "/actualizarPuesto",
    authorizationMiddleware,
    rolVerificatorMiddlewareJefePersonal,
    contentMiddlewarePuestos,
    putPuestosDTOMiddleware,
    actualizarPuestoController
  );
  router.put(
    "/actualizarSeguimientoEmpleado",
    authorizationMiddleware,
    rolVerificatorMiddlewareJefePersonal,
    contentMiddlewareSeguimientoEmpleados,
    putSeguimientoEmpleadoDTOMiddleware,
    actualizarSeguimientoEmpleadoController
  );
  router.put(
    "/actualizarTipoBoleta",
    authorizationMiddleware,
    rolVerificatorMiddlewareTaquillero,
    contentMiddlewareTipoBoleta,
    putTiposBoletasDTOMiddleware,
    actualizarTipoBoletaController
  );
  router.put(
    "/actualizarZona",
    authorizationMiddleware,
    rolVerificatorMiddlewareAdmin,
    contentMiddlewareZonas,
    putZonasDTOMiddleware,
    actualizarZonaController
  );
  return router;
};

export { putInitRoute };
